spring:
  application:
    name: challenge-iventis

hosts:
  mock:
    url: https://rgr3viiqdl8sikgv.public.blob.vercel-storage.com
    products-path: produtos-mnboX5IPl6VgG390FECTKqHsD9SkLS.json
    customers-path: clientes-Vz1U6aR3GTsjb3W8BRJhcNKmA81pVh.json